# Generated by Django 6.0.1 on 2026-01-31 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='bank_account',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='supplier_docs/'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='ifsc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('APPROVED', 'Approved')], default='PENDING', max_length=20),
        ),
    ]
