# Generated by Django 6.0.1 on 2026-01-31 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_supplier_bank_account_supplier_documents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Verification'), ('APPROVED', 'Approved')], default='PENDING', max_length=20),
        ),
    ]
