# Generated by Django 6.0.1 on 2026-02-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_alter_supplier_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='altitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='current_location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='list_of_material',
            field=models.CharField(blank=True, choices=[('CEMENT', 'Cement'), ('STEEL', 'Steel / TMT Bars'), ('SAND', 'Sand'), ('BRICKS', 'Bricks'), ('AGGREGATES', 'Aggregates'), ('RMC', 'Ready Mix Concrete'), ('TILES', 'Tiles'), ('MARBLE', 'Marble'), ('GRANITE', 'Granite'), ('PLYWOOD', 'Plywood'), ('HARDWARE', 'Hardware & Fasteners'), ('ELECTRICAL', 'Electrical Cables'), ('SWITCHES', 'Switches & Sockets'), ('PIPES', 'Pipes'), ('SANITARY', 'Sanitary Ware'), ('PAINTS', 'Paints & Coatings'), ('GLASS', 'Glass'), ('ALUMINIUM', 'Aluminium Sections'), ('BITUMEN', 'Bitumen'), ('ROOFING', 'Roofing Sheets')], max_length=50, null=True),
        ),
    ]
