# Generated by Django 6.0.1 on 2026-02-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
        ('suppliers', '0004_supplier_altitude_supplier_current_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='list_of_material',
        ),
        migrations.AddField(
            model_name='supplier',
            name='list_of_material',
            field=models.ManyToManyField(blank=True, to='materials.materials'),
        ),
    ]
