# Generated by Django 6.0.1 on 2026-02-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
        ('suppliers', '0005_remove_supplier_list_of_material_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='documents',
            new_name='aadhar',
        ),
        migrations.AddField(
            model_name='supplier',
            name='gst_certificate',
            field=models.FileField(blank=True, null=True, upload_to='supplier_docs/'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='pan',
            field=models.FileField(blank=True, null=True, upload_to='supplier_docs/'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='list_of_material',
            field=models.ManyToManyField(to='materials.materials'),
        ),
    ]
