# Generated by Django 6.0.1 on 2026-01-31 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_alter_invoice_amount_alter_invoice_invoice_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Verification'), ('APPROVED', 'Approved')], default='Pending', max_length=50),
        ),
    ]
